providers = ['node']

[variables]
  NODE_ENV = 'production'

[phases.setup]
  nixPkgs = ['nodejs', 'yarn']

[phases.install]
  cmds = ['yarn']

[phases.build]
  dependsOn = ['install']
  cmds = ['yarn build:web']

[phases.caddy]
  dependsOn = ['build']
  nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301' # Caddy v2.8.4
  nixPkgs = ['caddy']

[phases.fmt]
  dependsOn = ['caddy']
  cmds = ['caddy fmt --overwrite Caddyfile']

[start]
    cmd = 'exec caddy run --config Caddyfile --adapter caddyfile 2>&1'
