providers = ['node']

[variables]
  NODE_ENV = 'production'

[phases.setup]
  nixPkgs = ['nodejs', 'yarn']

[phases.install]
  nixPkgs = ['yarn install']

[phases.build]
  dependsOn = ['install']
  cmds = ['turbo build --filter=api --filter=./packages/*', 'cd api']

[start]
  cmd = 'yarn start'